#SPDX-License-Identifier: MIT-0
---
- name: Install k3s cluster
  hosts: cluster
  become: true

  tasks:
    - name: Install k3s in controlpanel
      include_role:
        name: k3s
        tasks_from: controlpanel_installation.yml
      when: "'controlpanels' in group_names"

    - name: Install k3s in workers
      include_role:
        name: k3s
        tasks_from: worker_installation.yml
      when: "'workers' in group_names"

- name: Install management tools in cms
  hosts: cms

  tasks:
    - name: Install k3s in workers
      include_role:
        name: k3s
        tasks_from: worker_installation.yml

   


