#SPDX-License-Identifier: MIT-0
---
- name: Deploy k3s kubeadmin
  hosts: kubeadmin
  become: true
  tasks:
    - name: Execute controlpanel_installation.yml
      include_role:
        name: k3s
        tasks_from: controlpanel_installation.yml

- name: Deploy k3s cluster 1
  hosts: cluster-1
  become: true
  tasks:
    - name: Execute controlpanel_installation.yml
      include_role:
        name: k3s
        tasks_from: controlpanel_installation.yml
      when: "'cluster-1-controlplanes' in group_names"

    - name: Execute worker_installation.yml 
      include_role:
        name: k3s
        tasks_from: worker_installation.yml
      when: "'cluster-1-workers' in group_names"

- name: Deploy k3s cluster 2
  hosts: cluster-2
  become: true
  tasks:
    - name: Execute controlpanel_installation.yml
      include_role:
        name: k3s
        tasks_from: controlpanel_installation.yml
      when: "'cluster-2-controlplanes' in group_names"

    - name: Execute worker_installation.yml
      include_role:
        name: k3s
        tasks_from: worker_installation.yml
      when: "'cluster-2-workers' in group_names"

- name: Install management tools in cms
  hosts: cms
  tasks:
    - name: Execute tools_installation.yml
      include_role:
        name: k3s
        tasks_from: tools_installation.yml

- name: Configurate kubeconfig in kubeadmin
  hosts: cms
  tasks:
    - name: Execute kubeconfig_configuration.yml
      include_role:
        name: k3s
        tasks_from: kubeconfig_configuration.yml