#SPDX-License-Identifier: MIT-0
---
- name: Install k3s in controlpanel
  hosts: controlpanel
  become: true
  tasks:
    - name: Execute k3s_installation.yml
      ansible.builtin.include_role:
        name: k3s
        tasks_from: controlpanel_installation.yml

- name: Install k3s in workers
  hosts: workers
  become: true
  tasks:
    - name: Execute k3s_installation.yml
      ansible.builtin.include_role:
        name: k3s
        tasks_from: workers_installation.yml


