#cloud-config
users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "$6$kmOnMk2fKWTrQgrd$fAN.celI2/ofFrEiCCt5WEQb0DENALCsD3fF3h7yW9SKRaP29Q06B3/EEe4fqZbuLmxL4Vqs/2Vt6RKcZpcS6."
    ssh_authorized_keys:
      - ${master_public_key}
package_update: true
package_upgrade: true
packages:
  - git
  - pipx
  - python3
  - fail2ban
  - ufw
timezone: Europe/Madrid
locale: es_ES.UTF-8
write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    permissions: '0640'
    owner: root:root
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      Port 2222
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      MaxAuthTries 2
      AllowTcpForwarding no
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      AllowUsers ansible
  - path: /home/ansible/.ssh/ansible_key
    permissions: '0600'
    owner: ansible:ansible
    content: |
      ${indent(6, ansible_private_key)}
runcmd:
  - printf "[sshd]\nenabled = true\nport = ssh, 2222\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow 2222
  - ufw enable
  - git clone https://github.com/Chenoveko/hetzner-project.git /home/ansible/project
  - chown -R ansible:ansible /home/ansible/project
  - pipx install --include-deps ansible
    
power_state:
  mode: reboot
  delay: now
  condition: true
