dns_hosts:
  - ip: 10.42.20.11
    hostnames:
      - cms
  - ip: 10.42.20.12
    hostnames:
      - controlpanel
  - ip: 10.42.20.13
    hostnames:
      - worker1
  - ip: 10.42.20.14
    hostnames:
      - worker2
  - ip: 10.42.20.14
    hostnames:
      - worker3