dns_hosts:
  - ip: 10.0.0.3
    hostnames:
      - master
  - ip: 10.0.0.4
    hostnames:
      - worker1
  - ip: 10.0.0.5
    hostnames:
      - worker2
  - ip: 10.0.0.6
    hostnames:
      - worker3
