#####################################
#          clamd on-access          #
#####################################
OnAccessExtraScanning no
OnAccessDisableDDD yes
OnAccessPrevention yes
OnAccessMaxFileSize 5M
OnAccessMaxThreads 5

# ===== On-access include paths ====#
OnAccessIncludePath /home
OnAccessIncludePath /root
OnAccessIncludePath /opt
OnAccessIncludePath /mnt
OnAccessIncludePath /media

# ===== On-access exclude paths ====#
OnAccessExcludePath /bin
OnAccessExcludePath /boot
OnAccessExcludePath /lib
OnAccessExcludePath /lib64
OnAccessExcludePath /proc
OnAccessExcludePath /run
OnAccessExcludePath /sbin
OnAccessExcludePath /sys
OnAccessExcludePath /usr
OnAccessExcludePath /etc
OnAccessExcludePath /dev
OnAccessExcludePath /afs
OnAccessExcludePath /srv
OnAccessExcludePath /var
OnAccessExcludePath /tmp

# ===== On-access exclude users ====#
OnAccessExcludeUname clamav
OnAccessExcludeRootUID no