#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k3s
- name: Download script installation of k3s
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Check if k3s-uninstall script exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_uninstall

- name: Uninstall previous k3s server
  ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
  when: k3s_uninstall.stat.exists

- name: Gather hostname fact
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "platform"
    filter:
      - ansible_hostname

- name: Execute installation of k3s in controlpanel
  ansible.builtin.command: /tmp/k3s_install.sh
  environment:
    INSTALL_K3S_EXEC: "--tls-san {{ ansible_hostname }}"
  args:
    creates: /usr/local/bin/k3s

- name: Read k3s token from controlpanel
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_file

- name: Set k3s token fact
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token_file.content | b64decode | trim }}"

- name: Remove installation script of k3s
  ansible.builtin.file:
    path: /tmp/k3s_install.sh
    state: absent

- name: Allow k3s API port in UFW
  community.general.ufw:
    rule: allow
    port: '6443'
    proto: tcp
    src: 10.42.20.0/24