#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k3s
- name: Download script installation of k3s
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Install k3s agent on workers
  ansible.builtin.command: /tmp/k3s_install.sh
  environment:
    K3S_URL: "https://controlpanel:6443"
    K3S_TOKEN: "{{ k3s_token }}"

- name: Remove installation script of k3s
  ansible.builtin.file:
    path: /tmp/k3s_install.sh
    state: absent