#SPDX-License-Identifier: MIT-0
---
- name: Install Homebrew
  hosts: kubeadmin
  tasks:
    - name: Execute brew_installation.yml
      ansible.builtin.include_role:
        name: brew
        tasks_from: brew_installation.yml