#SPDX-License-Identifier: MIT-0
---
- name: Update /etc/hosts on cms first
  hosts: cms
  become: true
  roles:
    - dns

- name: Update /etc/hosts on the rest of machines
  hosts: linux:!cms
  become: true
  roles:
    - dns
