#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dns
- name: Deploy /etc/hosts from template
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  become: true
