#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dns
- name: Deploy /etc/hosts from template
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: "{{ lookup('template', 'hosts.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    owner: root
    group: root
    mode: '0644'
  become: true
