#SPDX-License-Identifier: MIT-0
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
    
- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: yes